#!/bin/bash
mkdir keep-alive
cd keep-alive
for i in {1..9}
do
	wget http://lolin1-data-provider-eu$i.herokuapp.com/services/champions/list?realm=na&locale=en_US
done
for j in {1..1}
do
	wget http://lolin1-data-provider-usa$j.herokuapp.com/services/champions/list?realm=na&locale=en_US
done
cd ..
rm -rf keep-alive